export {
  connectDatabase,
  createPrismaClient,
  disconnectDatabase,
  getPrismaClient,
  type PrismaClientInstance,
  setPrismaClientForTests,
} from './client.js';
export {
  type DatabaseEnv,
  DatabaseEnvError,
  databaseEnvSchema,
  loadDatabaseEnv,
} from './config.js';
export {
  IngestionValidationError,
  validateIngestionCounts,
  validateIngestionSourceUri,
  validateNonNegativeCount,
  validateSourceIdentifier,
} from './domain/ingestion-validation.js';
export {
  buildStorageKeyPlaceholder,
  type ChecksumAlgorithm,
  MediaValidationError,
  sanitizeFilenameForStorageKey,
  SUPPORTED_CHECKSUM_ALGORITHMS,
  validateChecksum,
  validateChecksumAlgorithm,
  validateMetadataKey,
  validateMetadataNamespace,
  validateMimeType,
  validateSha256Checksum,
  validateStorageKey,
} from './domain/media-validation.js';
export {
  PRIORITY_MAX,
  PRIORITY_MIN,
  ProcessingValidationError,
  validateArtifactChecksum,
  validateArtifactCompatibility,
  validateArtifactMimeType,
  validatePriority,
  validateRetryCount,
  validateStorageKeyPlaceholder,
} from './domain/processing-validation.js';
export { checkDatabaseHealth, type DatabaseHealthResult } from './health.js';
export {
  activeRecordsFilter,
  type ActorRef,
  appendAuditLog,
  type AppendAuditLogInput,
  AssetRepository,
  type AuditAction,
  type AuditLogEntry,
  AuditLogRepository,
  ContentItemRepository,
  type CreateIngestionJobInput,
  type CreateIngestionSourceInput,
  type CreateMediaAssetInput,
  type CreateMediaSourceInput,
  type CreateProcessingArtifactInput,
  type CreateProcessingJobInput,
  IngestionJobRepository,
  IngestionSourceRepository,
  MediaAssetRepository,
  MediaSourceRepository,
  MetadataRecordRepository,
  OrganizationRepository,
  ProcessingArtifactRepository,
  ProcessingJobRepository,
  ProjectRepository,
  ProjectScopeError,
  requireOrganizationId,
  requireProjectId,
  type UpdateIngestionJobProgressInput,
  type UpdateIngestionSourceInput,
  type UpdateMediaAssetMetadataInput,
  type UpdateProcessingJobInput,
  type UpsertMetadataRecordInput,
} from './repositories/index.js';
export type {
  AiJob,
  AnalyticsSnapshot,
  ArtifactType,
  Asset,
  AssetStatus,
  ContentItem,
  ContentState,
  ContentType,
  ContentVersion,
  IngestionJob,
  IngestionSource,
  IngestionSourceType,
  IngestionStatus,
  MediaSource,
  MediaSourceType,
  MetadataRecord,
  Organization,
  OutboxAction,
  OutboxStatus,
  ProcessingArtifact,
  ProcessingJob,
  ProcessingStatus,
  ProcessingType,
  Project,
  PublishingOutboxEntry,
  PublishRecord,
  SeoProfile,
} from '@prisma/client';
export { Prisma } from '@prisma/client';
