export {
  connectDatabase,
  createPrismaClient,
  disconnectDatabase,
  getPrismaClient,
  type PrismaClientInstance,
  setPrismaClientForTests,
} from './client.js';
export {
  type DatabaseEnv,
  DatabaseEnvError,
  databaseEnvSchema,
  loadDatabaseEnv,
} from './config.js';
export {
  buildStorageKeyPlaceholder,
  type ChecksumAlgorithm,
  MediaValidationError,
  sanitizeFilenameForStorageKey,
  SUPPORTED_CHECKSUM_ALGORITHMS,
  validateChecksum,
  validateChecksumAlgorithm,
  validateMetadataKey,
  validateMetadataNamespace,
  validateMimeType,
  validateSha256Checksum,
  validateStorageKey,
} from './domain/media-validation.js';
export { checkDatabaseHealth, type DatabaseHealthResult } from './health.js';
export {
  activeRecordsFilter,
  type ActorRef,
  appendAuditLog,
  type AppendAuditLogInput,
  AssetRepository,
  type AuditAction,
  type AuditLogEntry,
  AuditLogRepository,
  ContentItemRepository,
  type CreateMediaAssetInput,
  type CreateMediaSourceInput,
  MediaAssetRepository,
  MediaSourceRepository,
  MetadataRecordRepository,
  OrganizationRepository,
  ProjectRepository,
  ProjectScopeError,
  requireOrganizationId,
  requireProjectId,
  type UpdateMediaAssetMetadataInput,
  type UpsertMetadataRecordInput,
} from './repositories/index.js';
export type {
  AiJob,
  AnalyticsSnapshot,
  Asset,
  AssetStatus,
  ContentItem,
  ContentState,
  ContentType,
  ContentVersion,
  MediaSource,
  MediaSourceType,
  MetadataRecord,
  Organization,
  OutboxAction,
  OutboxStatus,
  Project,
  PublishingOutboxEntry,
  PublishRecord,
  SeoProfile,
} from '@prisma/client';
export { Prisma } from '@prisma/client';
